r"""
generated by json2python-models v0.2.5 at Mon Apr 25 07:46:15 2022
command: /Users/jeanpaul.weijers/Code/clockify-api/.venv/bin/json2models -f pydantic -l Client - client.json
"""
from pydantic import BaseModel, Field
from typing import Literal, Optional


class Client(BaseModel):
    id_: str = None
    name: str
    workspace_id: str
    archived: bool = False

    class Config:
        allow_population_by_field_name = True
        fields = {"id_": "id", "workspace_id": "workspaceId"}


class ClientGetParams(BaseModel):
    archived: bool = None
    name: str = None
    page: int = 1
    page_size: int = 50
    sort_column: Literal["NAME"] = None
    sort_order: Literal["ASCENDING", "DESCENDING"] = None

    class Config:
        allow_population_by_field_name = True
        fields = {
            "page_size": "page-size",
            "sort_column": "sort-column",
            "sort_order": "sort-order",
        }


class ClientUpdateParams(BaseModel):
    archive_projects: bool = None

    class Config:
        allow_population_by_field_name = True
        fields = {"archive_projects": "archive-projects"}
