r"""
generated by json2python-models v0.2.5 at Mon Apr 25 07:46:15 2022
command: /Users/jeanpaul.weijers/Code/clockify-api/.venv/bin/json2models -f pydantic -l Client - client.json
"""
from pydantic import BaseModel, Field
from typing import Optional


class Client(BaseModel):
    id_: str = None
    name: str
    workspace_id: str
    archived: bool = False

    class Config:
        allow_population_by_field_name = True
        fields = {"id_": "id", "workspace_id": "workspaceId"}


class ClientQuery:
    pass
